apiVersion: v1
kind: Service
metadata:
  labels:
    app: weather-server
  name: weather-server
  namespace: tls-demo
spec:
  ports:
  - port: 80
    targetPort: http
    name: http
  - port: 443
    name: https
    targetPort: https
  selector:
    app: weather-server