apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: issuer-trust-bundle
  namespace: cert-manager
spec:
  sources:
    - secret:
        name: "ca-certificate-secret"
        key: "ca.crt"
  target:
    namespaceSelector: {}
    configMap:
      key: "trust-bundle.pem"
