apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: tlstest-server-certificate
    namespace: tls-demo
spec:
    duration: 1h10m
    renewBefore: 50m
    commonName: weather-server
    dnsNames:
        - weather-server
        - weather-server.tls-demo
        - weather-server.tls-demo.svc
        - weather-server.tls-demo.svc.cluster.local
    issuerRef:
        name: server-cert-issuer
        kind: ClusterIssuer
    secretName: weather-server-certificate
